[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "9a5a3b655cedb42e4763d501b6e950f3cf6dfc4b"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "c201212962c06139e63753d3824edcb475e20e20816db04af234750f1e51a85f"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.aarch64-linux-gnu.tar.gz"
[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "bea81c55af43c1bf11e8e53a6e3d72dc76cabc4e"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "dc7e7c44dc40f119419fc04d57a1bb1b50f5f8948bdb4b3f2a181ec90777784f"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.aarch64-linux-musl.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed60ccffe1620d854cb6c8068f0e927e2de950e8"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "d8965823c9c620b78801cb81054e5313fe00c0a8ced71cf71f936cfdb3cc7bdc"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.armv7l-linux-gnueabihf.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b0bb1716e3fc691e74da273a0a11aee0d9d324f"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "308614398020407aecc55003fd742435ca0c88b96e0ac339356f4b1a9ca21d95"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.armv7l-linux-musleabihf.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "17813614076c5a910b8d40beed540a0c9dfd226f"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "be0dd32143d7d14b1021d2037b63be36c4c5478992c5c31ee4172703ae931085"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.i686-linux-gnu.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "6f7f1b3e740a4266de2def5ec102ad8805c47d02"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "c650cebd425a73715edca562482349117b0fd9b5f4d99bef5a76bf9a469e4242"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.i686-linux-musl.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "56d2ca4fb45f30094cf752d4040645aa2bfe05de"
os = "windows"

    [[hidapi.download]]
    sha256 = "4facbaf7ed51a3e2008c88b6b860ee1545e1922163c06024bc4c9916d221d64a"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.i686-w64-mingw32.tar.gz"
[[hidapi]]
arch = "powerpc64le"
git-tree-sha1 = "b9afdfaf5ef96f4ef8526e0f7e97688fa2004618"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "251c9cf20da2c2d806d6643f8e0c955314b8064baddcf31354f1ec421aa1c200"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.powerpc64le-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "084b54dba83498383c889491b98ab04bd5f5472f"
os = "macos"

    [[hidapi.download]]
    sha256 = "3004cca50bd48b65e6dfc7314024d7f49c394f9cbf4c8bbb9d44897b842f9249"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.x86_64-apple-darwin.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "97ef7a77d3c631d4d4b33b6417326f86350a5ee1"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "fa21e0a0310a50bfe5ac91f44e544103e5a0f8e822958c920261e7e9b4c476b0"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.x86_64-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "03763e59851e22cc618150652c0115022bc9fed6"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "4eac74405411b25465bd317dbbc278c9481f7cc557e6308c53d866c941fb88b9"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.x86_64-linux-musl.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "9e8f505bf93b00b4f39841a5a2ef792aa5ae435e"
os = "windows"

    [[hidapi.download]]
    sha256 = "586fdfd9a886b4f68fb124b226afa4b0b5cb41a5234e9958696022d882e352e9"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.10.1+0/hidapi.v0.10.1.x86_64-w64-mingw32.tar.gz"
