[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "7dda3c116ad8fd24119430a9d3855b2c8af2375b"
os = "macos"

    [[hidapi.download]]
    sha256 = "e20e24c0148a76c7872b02df25a526ab6aeff971c67ed5e8b2d0ba4ac2a15a32"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.aarch64-apple-darwin.tar.gz"
[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "d2c8d373c2068410ffe627f493827e8bba6524d9"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "f8d8d36381b9e37292fe1760881f12a90ae74afede46cf3d046ac07e4805e564"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.aarch64-linux-gnu.tar.gz"
[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "ebca13c16ae3bae275fefc04b97454e3742e200c"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "e45d6a739390b81a7bbc1468bf2519da2158ebe9597ea0b6cc014421d3c63ed5"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.aarch64-linux-musl.tar.gz"
[[hidapi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80bd154185d2a01fdef9a28fab5ab4a46ce9b36f"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "44b6646a36442d65e37214d9334322e92792534c0f17446e881c66522974b07b"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.armv6l-linux-gnueabihf.tar.gz"
[[hidapi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ed2b02cdd1e0fa2c557971a184662a918dfa076"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "3ae45682f4dd5e458f2ddc2481a736b7f27cb527a9b72393fd797518e5df1dec"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.armv6l-linux-musleabihf.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b55fbf0d5c650efdd4f376353ca6e97f3e54f47"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "44cf5e9a9bf962cfb2812c37fcead53ab496790faf55de5c23788bc9c10ed185"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.armv7l-linux-gnueabihf.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe6477793a03c036332f46ebe78dc1baad9a076b"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "5bd44e81938048645e354022cb669c0b67795900471f2df1161ac503fa3be458"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.armv7l-linux-musleabihf.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "79ba89a4eb0b002076e673e735e98f3d8417c5d8"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "0e8a57034d8d2dcd010a22985ce3b5eaf6343ad1da3c6e1a2682f02a06c86ebe"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.i686-linux-gnu.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "1d24b145c0775f9de44f268646b41e91b05a44a3"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "8d039d3e85b8251b1a03a93d43f5882e3622a705712e32f0da1f5e38ed7ac7a1"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.i686-linux-musl.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "7b18c49444ca8d7810eb2624438a3884cd7fc64a"
os = "windows"

    [[hidapi.download]]
    sha256 = "b198516775966415c5bdb03e3462eb54abbddeca7dd26e82bbb956784e60a051"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.i686-w64-mingw32.tar.gz"
[[hidapi]]
arch = "powerpc64le"
git-tree-sha1 = "025f98ab9ea41f737e1ae4a9273300a6d64e8936"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "a69e8916b70c7b5ae002a7effda875dffe86c58c8b494cf4d767d37029d96025"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.powerpc64le-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "b2fdebae83534951a9b1870779594dbb2bc5726c"
os = "macos"

    [[hidapi.download]]
    sha256 = "35cd6c2c19bc221630f885460e4cd346e7d235d6605cdbd971d6924e25d8f5f1"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.x86_64-apple-darwin.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "7286e823708c4c808f6cd41938f1229239cd7e2a"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "9bf8dbbbd6ffa2720af5c784edb6578ee58c953910b768f19ba69c7eb86837b4"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.x86_64-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "b75618aa13d8e4aecd07243f3ae3818993a4cca5"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "f7c0513f7157ed2ea541b731d4c1ed3a69ba00c61fad45d0e76aeedaec63acc0"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.x86_64-linux-musl.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "69c43c30377b4fabde5435f405bfc53d34fcd74c"
os = "freebsd"

    [[hidapi.download]]
    sha256 = "1c18f3636f5f3aa57a667e6c1a0b2dc7eaa47b42629b1d5d9a4b2416e9d2afcb"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.x86_64-unknown-freebsd.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "c74127079d3fdb1b2f9e78e31f41c618ea3fde5c"
os = "windows"

    [[hidapi.download]]
    sha256 = "34823b02ea9d3bcad728a6a1e7ce5a58a896044227409bb84697d578d7a71df7"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.13.1+0/hidapi.v0.13.1.x86_64-w64-mingw32.tar.gz"
