[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "16058f7019597f2c2a928a2ff752767e509cea7c"
os = "macos"

    [[hidapi.download]]
    sha256 = "ffeeda74055e5825b85ef0f9a07bf72d93c67199076a554afb10342474654c40"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.aarch64-apple-darwin.tar.gz"
[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "d513c3c5d5db0406c5280b6527f486032ff7d637"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "6443980ab62744037e8d28e02ee85d691c5a8d9a945324f5273d6a73df286cc2"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.aarch64-linux-gnu.tar.gz"
[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "434446e8b0e352296185a61df25e67d5eae43694"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "4a8cb47c59974e3e31c5908a9a370adceec46d57058809b8dc0fc2b4ed9e1491"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.aarch64-linux-musl.tar.gz"
[[hidapi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03995b88d2c10b8d72291a80f7e038c70d2ad935"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "86ae65fd0c97ce20b0aeae8dc32c53ff6c02210129d672a2c580ec7d9ed43c94"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.armv6l-linux-gnueabihf.tar.gz"
[[hidapi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2514d4fa4c7a99794d09a856ede7479fa443013"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "cefa2ed2ce366f8a909bf4bf5fa525783861c7d733b3f221b71ece76ad5fb3fc"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.armv6l-linux-musleabihf.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7b94ac35990edbc57042b1714dd57ec82111775"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "6371a36b8fd9434ca4cfd49fbe7f68bf8109939f14156416d2e129b3301f0966"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.armv7l-linux-gnueabihf.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50a9be8b2e9ccdf00e898c95bfb324bf1444d3da"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "1245333d6ac5b7897f8d452219dc3cbce5ccedfe7a24590874e668daf5a2a54f"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.armv7l-linux-musleabihf.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "4161af13730743e730b6f7e1d8c580f6477c9170"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "672c8e7582c4ee7b7a7a5d74a0ac2f4fe57982b27d033fbfa4473f7c79bf3601"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.i686-linux-gnu.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "8a1584e97b36b943196a1ffa04042490fc830776"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "1e70e814660359c64cbc4456910fa02cafc27a7c34023168717d50d8a518a90f"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.i686-linux-musl.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "43d7501bd3d2d4055085db3cae69e4c8f990139c"
os = "windows"

    [[hidapi.download]]
    sha256 = "f6474907e9ad30d94a52c3d0dd05cfcc1397d3d79847b83ee9d096e06e715e25"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.i686-w64-mingw32.tar.gz"
[[hidapi]]
arch = "powerpc64le"
git-tree-sha1 = "46a410c6237747d066ab8308061e7b801c9176bd"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "20ec49ba54b1219b79364a68fe4313ac1dab709491f6599c69d2f7c086a7d33a"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.powerpc64le-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "f95a741dd2609954ddfbb87006bc5a1511658e84"
os = "macos"

    [[hidapi.download]]
    sha256 = "d7dd21b785a5c7e5de54b13b589a814c47794042560f0d538a05cfc6b64e700a"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.x86_64-apple-darwin.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "38da3b1fade8bfddd0482bb874ca7f4feb609693"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "903c9eac08450eb0c62d3d32f653c746df2b3ad489f1771af149690d1cad9396"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.x86_64-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "1025110c442ca0f8c47b2db99feaffecee7af569"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "e6c4513134feda7cc8d1decd91cf08f8263f4bb4b08f2659965447e1c08f08d3"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.x86_64-linux-musl.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "83d5d227fbda0bfae5f88088d8f2d66d12df2a39"
os = "windows"

    [[hidapi.download]]
    sha256 = "30f9f6dc7782e7b39cc4335bd84ad4f9d09ab4a23dc7ecb06d50b5c10ada9fdf"
    url = "https://github.com/JuliaBinaryWrappers/hidapi_jll.jl/releases/download/hidapi-v0.11.2+0/hidapi.v0.11.2.x86_64-w64-mingw32.tar.gz"
